export const GET_CATEGORY_LIST ="GET_CATEGORY_LIST";
export const GET_BILLER_CATEGORY_LIST ="GET_BILLER_CATEGORY_LIST";
export const GET_BILLER_PRODUCT_LIST ="GET_BILLER_PRODUCT_LIST";
export const BILLER_VALIDATION ="BILLER_VALIDATION";
export const GOTO_PRODUCTLIST ="GOTO_PRODUCTLIST";
export const GOTO_BILLERVALIDATION ="GOTO_BILLERVALIDATION";
export const BILLER_PAYMENT ="BILLER_PAYMENT";



export const SET_LOADING ="SET_LOADING";
export const STOP_LOADING ="STOP_LOADING";



